### ISSUE TITLE
File.exists? is undefined

### ISSUE THREAD

**Issue by Semicolon7645** [clnhlzmn/jekyll-pig#3]
It appears `File.exists?` is deprecated and not longer exists: https://docs.ruby-lang.org/en/3.2/File.html

Ruby Version: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x64-mingw-ucrt]

```
C:/Users/Collin/Documents/Nerf/WNYNC/current_wnync.com/wnync_com/assets/ruby/jekyll-pig-ccm/lib/jekyll-pig.rb:217:in `make_output_paths': undefined method `exists?' for File:Class (NoMethodError)

            FileUtils.mkdir_p @assets_path unless File.exists? @assets_path
                                                      ^^^^^^^^
Did you mean?  exist?
        from C:/Users/Collin/Documents/Nerf/WNYNC/current_wnync.com/wnync_com/assets/ruby/jekyll-pig-ccm/lib/jekyll-pig.rb:245:in `generate'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:193:in `block in generate'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:191:in `each'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:191:in `generate'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:79:in `process'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from C:/Users/Collin/.local/share/gem/ruby/3.2.0/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
        from C:/Ruby/Ruby32-x64/bin/jekyll:32:in `load'
        from C:/Ruby/Ruby32-x64/bin/jekyll:32:in `<main>'
```

**Comment by Semicolon7645** [comment]
Changing to `File.exist?` resolves the issue.
